const SET_CURRENT_USER = "SET_CURRENT_USER";
const GET_REPORTS = "GET_REPORTS";
const GET_FAUNA = "GET_FAUNA";
const GET_FLORA = "GET_FLORA";
const SET_REGISTER = "SET_REGISTER";
export { SET_CURRENT_USER, GET_REPORTS, GET_FAUNA, GET_FLORA, SET_REGISTER}
